name: ner_model
channels:
- pytorch
- HuggingFace
- comet_ml
- conda-forge
dependencies:
- python=3.10
- comet_ml
- datasets
- matplotlib
- pandas
- pip
- pytorch
- scikit-learn
- tqdm
- thefuzz
- transformers
- unidecode